// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesDataCore;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MoviesDataCore.Migrations
{
    [DbContext(typeof(MoviesPlaceContext))]
    [Migration("20190209172006_First Migration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MoviesDomain.Models.Comment", b =>
                {
                    b.Property<int>("PostID");

                    b.Property<int>("UserID");

                    b.Property<int>("CommentID");

                    b.Property<string>("Content")
                        .IsRequired();

                    b.HasKey("PostID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            PostID = 1,
                            UserID = 1,
                            CommentID = 1,
                            Content = "I do not think that this movie was as good as you had rated it though"
                        },
                        new
                        {
                            PostID = 1,
                            UserID = 2,
                            CommentID = 2,
                            Content = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."
                        });
                });

            modelBuilder.Entity("MoviesDomain.Models.Favorite", b =>
                {
                    b.Property<int>("MovieID");

                    b.Property<int>("UserID");

                    b.Property<int>("FavoriteID");

                    b.Property<string>("Note");

                    b.HasKey("MovieID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MoviesDomain.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("MovieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Title = "Avangers"
                        });
                });

            modelBuilder.Entity("MoviesDomain.Models.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<int>("MovieID");

                    b.Property<DateTime>("PostDate");

                    b.Property<int>("Rating");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("UserID");

                    b.HasKey("PostID");

                    b.HasIndex("MovieID");

                    b.HasIndex("UserID");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostID = 1,
                            Description = "Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance.",
                            MovieID = 1,
                            PostDate = new DateTime(2019, 2, 9, 12, 20, 6, 152, DateTimeKind.Local).AddTicks(1883),
                            Rating = 4,
                            Title = "I really liked watching her laugh",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("MoviesDomain.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "scotty@gmail.com",
                            Password = "*****",
                            Username = "scatman"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "levi@gmail.com",
                            Password = "*****",
                            Username = "gatesman"
                        });
                });

            modelBuilder.Entity("MoviesDomain.Models.Comment", b =>
                {
                    b.HasOne("MoviesDomain.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoviesDomain.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoviesDomain.Models.Favorite", b =>
                {
                    b.HasOne("MoviesDomain.Models.Movie", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoviesDomain.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MoviesDomain.Models.Post", b =>
                {
                    b.HasOne("MoviesDomain.Models.Movie", "Movie")
                        .WithMany("Posts")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoviesDomain.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
